export const CATEGORIES: Record<string, string> = {
  'beauty': "Красота",
  'fragrances': "Ароматы",
  'furniture': "Мебель",
  'groceries': "Продукты",
  'home-decoration': "Домашний декор",
  'kitchen-accessories': "Товары для кухни",
  'laptops': "Ноутбуки",
  'mens-shirts': "Мужские рубашки",
  'mens-shoes': "Мужская обувь",
  'mens-watches': "Мужские часы",
  'mobile-accessories': "Мобильные аксессуары",
  'motorcycle': "Мотоциклы",
  'skin-care': "Уход за кожей",
  'smartphones': "Смартфоны",
  'sports-accessories': "Спортивные аксессуары",
  'sunglasses': "Солнечные очки",
  'tablets': "Планшеты",
  'tops': "Топы",
  'vehicle': "Транспорт",
  'womens-bags': "Женские сумки",
  'womens-dresses': "Женские платья",
  'womens-jewellery': "Женские украшения",
  'womens-shoes': "Женская обувь",
  'womens-watches': "Женские часы",
};